### ISSUE TITLE
Document what is the value of maxrss field when not available?

### ISSUE THREAD

**Issue by stepancheg** [lu-zero/wait4-rs#2]
Currently it says:

```
    /// Maximum resident set size
    ///
    /// Expressed in bytes when available.
    pub maxrss: u64,
```

What is the value when it is not available? Should it be `None` to mark the value is not available?

Also, it is not very clear it is in bytes, not in megabytes. Could be:

```
    /// Maximum resident set size, in bytes.
    ///
    /// `None` when not available.
    pub maxrss: Option<u64>,
```

**Comment by lu-zero** [comment]
It is 0, I'd rather avoid Option in those cases. Ideally all the platforms supported provide the maxrss.

I'll update the documentation soon, thank you for noticing.
